### ISSUE TITLE
Installing ORF finder

### ISSUE THREAD

**Issue by rotifergirl** [andrewgull/MGERT#1]
Hi,

I'd like to get MGERT up and running, but I can't find any instructions for getting ORF finder up and running. I've downloaded to ORFfinder.gz file from NCBI, but what else do I need to do with it for it to work?

Thanks!
Julie

**Comment by andrewgull** [comment]
Hi Julie!
gunzip _ORFfinder.gz_ file and then make it executable with `chmod +x ORFfinder` command.
After that, you will be able to run it

Also, make sure that ORFfinder executable is somewhere in your PATH in order to MGERT could find it
