### ISSUE TITLE
Could MGERT annotate the full structure of DIRS/DIRS?

### ISSUE THREAD

**Issue by wangj2009** [andrewgull/MGERT#2]
Hi, 
    I want to clarify the boundary and inverted ITRs of DIRS in my genomic contigs. Could MGERT help me to mine it? Like the attached sequences,
[potential-DIRS-cae-genome-40-d.fa.docx](https://github.com/andrewgull/MGERT/files/3726925/potential-DIRS-cae-genome-40-d.fa.docx)

    Thanks a lot,

**Comment by andrewgull** [comment]
Hi!
Yes, I think it can. Try to run it on a genome (scaffold/contig) of interest
